import "./globals.css";

export const metadata = {
  title: "Project Task Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-3">
        <header>
          <h1 className="font-semibold text-xl text-center mt-3">
            Project Task Tracker
          </h1>
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}

// <header><h1>Task Tracker</h1></header>
//     <main>
//       <div id="task-creation">
//         <input id="new-task-title" type="text" placeholder="Title" />
//         <button id="add-task">
//           <img src="icons/plus-circle.svg" alt="add task" />
//         </button>
//       </div>
//       <div id="tasks">
//         <!-- <div class="task">
//           <div class="task-title">Task 1</div>
//           <input type="checkbox" />
//           <button>
//             <img src="images/x-circle.svg" alt="delete task" />
//           </button>
//         </div>
//         <div class="task complete">
//           <div class="task-title">Task 2</div>
//            <input type="checkbox" />
//           <button>
//             <img src="images/x-circle.svg" alt="delete task" />
//           </button>
//         </div>
//         <div class="task">
//           <div class="task-title">Task 3</div>
//           <input type="checkbox" />
//           <button>
//             <img src="images/x-circle.svg" alt="delete task" />
//           </button>
//         </div>
//         <div class="task complete">
//           <div class="task-title">Task 4</div>
//           <input type="checkbox" />
//           <button>
//             <img src="images/x-circle.svg" alt="delete task" />
//           </button>
//         </div>
//         <div class="task">
//           <div class="task-title">Task 5</div>
//           <input type="checkbox" />
//           <button>
//             <img src="images/x-circle.svg" alt="delete task" />
//           </button>
//         </div> -->
//       </div>
//       <div id="task-reset" class="hidden">
//         <button id="clear-tasks">
//           <img src="icons/trash.svg" alt="delete task" />
//         </button>
//       </div>
//     </main>
//     <footer></footer>
