import "./globals.css";
import { Source_Sans_3 } from "next/font/google";

const sans = Source_Sans_3({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sans.className} mx-auto max-w-md`}>{children}</body>
    </html>
  );
}
