import "./globals.css";
import Header from "./header.js";
import Footer from "./footer.js";

export const metadata = {
  title: "Green Bank",
  description: "Generated by the green mob!",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
