import "./globals.css";

export const metadata = {
  title: "Green Bank",
  description: "Generated by the green mob!",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
